"""P2: evidence-channel labels derived from source location, not graph assertions.

These are delivery *policies*, not runtime-truth or source-proven relationships.
Unknown locations remain a distinct unknown channel, never a fabricated file.
Classify migration before tests (test fixtures can contain migration files).
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Dict, Iterable, Mapping, Optional

IMPLEMENTATION = "implementation"
TEST = "test"
MIGRATION = "migration"
VENDOR = "vendor_generated"
DOCUMENTATION = "documentation"
CONFIGURATION = "configuration"
UNKNOWN = "unknown"
CHANNELS = (IMPLEMENTATION, TEST, MIGRATION, VENDOR, DOCUMENTATION, CONFIGURATION, UNKNOWN)

_TEST_DIRS = {"tests", "test", "__tests__", "spec", "specs", "e2e", "integration_tests"}
_VENDOR_DIRS = {
    "vendor", "vendors", "third_party", "third-party", "node_modules",
    "dist", "build", "coverage", ".next", "_generated", "generated",
}
_CONFIG_NAMES = {
    "pyproject.toml", "setup.cfg", "setup.py", "tox.ini", "pytest.ini",
    "package.json", "package-lock.json", "yarn.lock", "requirements.txt",
    "pipfile", "pipfile.lock", "dockerfile", "makefile",
    "tsconfig.json", "ruff.toml", ".pre-commit-config.yaml",
}
_DOCUMENTATION_DIRS = {"docs", "doc", "documentation"}
_IMPLEMENTATION_SUFFIXES = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".rs", ".go", ".java", ".kt", ".cs",
    ".c", ".cc", ".cpp", ".h", ".hpp", ".rb", ".php", ".swift", ".sh", ".html",
    ".htm", ".css", ".sql", ".vue", ".svelte",
}
_TEST_SUFFIXES = ("_test.py", "_tests.py", ".test.js", ".spec.js", ".test.ts",
                  ".spec.ts", ".test.tsx", ".spec.tsx", "_test.go", "_test.rs")


def file_channel(path: Optional[str]) -> str:
    """Conservative, deterministic source-role label for delivery accounting.

    A test-like *symbol name* cannot make an implementation file a test.
    A source-backed node remains equally valid regardless of role.
    """
    if not path:
        return UNKNOWN
    normalized = str(path).replace("\\", "/").strip("/").lower()
    parts = PurePosixPath(normalized).parts
    filename = parts[-1] if parts else ""
    if (
        any(part in _VENDOR_DIRS for part in parts)
        or filename.endswith((".min.js", ".min.css", ".map", ".lock"))
        or filename.startswith(("generated_", "autogenerated_"))
    ):
        return VENDOR
    if "migrations" in parts or (
        filename.startswith(("migration_", "migrate_"))
        and filename.endswith((".py", ".sql", ".js", ".ts"))
    ):
        return MIGRATION
    if (
        any(part in _TEST_DIRS for part in parts)
        or filename.startswith(("test_", "spec_"))
        or filename in {"test.py", "tests.py", "conftest.py"}
        or filename.endswith(_TEST_SUFFIXES)
    ):
        return TEST
    if filename in _CONFIG_NAMES:
        return CONFIGURATION
    if (
        any(part in _DOCUMENTATION_DIRS for part in parts)
        or filename.endswith((".md", ".rst", ".adoc"))
    ):
        return DOCUMENTATION
    if PurePosixPath(filename).suffix not in _IMPLEMENTATION_SUFFIXES:
        return CONFIGURATION
    return IMPLEMENTATION


@dataclass(frozen=True)
class DeliveryChannelPolicy:
    """Opt-in selection preferences; original legacy packing remains default.

    The source-code implementation floor is *conditional on activation*. No
    gold essential-file label, repository name, or target symbol is consulted.
    max_test_fraction is a cap on selected test *nodes*, not a token estimate.
    """
    mode: str = "implementation_first"
    min_implementation_files: int = 2
    max_test_fraction: float = 0.35

    def normalized(self) -> "DeliveryChannelPolicy":
        if self.mode not in {"implementation_first", "symbol_evidence"}:
            raise ValueError("unsupported delivery channel policy: %r" % self.mode)
        fraction = float(self.max_test_fraction)
        if not 0.0 <= fraction <= 1.0:
            raise ValueError("max_test_fraction must be in [0, 1]")
        count = int(self.min_implementation_files)
        if not 0 <= count <= 8:
            raise ValueError("min_implementation_files must be between 0 and 8")
        return DeliveryChannelPolicy(
            mode=self.mode,
            min_implementation_files=count,
            max_test_fraction=fraction,
        )


def channel_counts(nodes: Iterable[object]) -> Dict[str, int]:
    counts = {channel: 0 for channel in CHANNELS}
    for node in nodes:
        location = getattr(node, "location", None)
        channel = file_channel(getattr(location, "path", None))
        counts[channel] += 1
    return {name: count for name, count in counts.items() if count}


def task_channel(query: str) -> str:
    """Only explicit request vocabulary overrides implementation-first default."""
    tokens = {
        token for token in "".join(
            char.lower() if char.isalnum() else " " for char in str(query)
        ).split() if token
    }
    if tokens & {"test", "tests", "testing", "pytest", "assertion",
                 "assertions", "fixture", "fixtures", "coverage", "spec"}:
        return TEST
    if tokens & {"migration", "migrations", "migrate", "alembic"}:
        return MIGRATION
    if tokens & {"vendor", "vendored", "generated", "bundle", "minified"}:
        return VENDOR
    return IMPLEMENTATION
